# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    mac:
      imageName: 'macos-10.13'
      target: "x86_64-apple-darwin"
    linux-amd64:
      imageName: 'ubuntu-16.04'
      target: "x86_64-unknown-linux-musl"
    linux-arm64:
      imageName: 'ubuntu-16.04'
      target: "aarch64-unknown-linux-gnu"
    linux-armhf:
      imageName: 'ubuntu-16.04'
      target: "armv7-unknown-linux-musleabihf"
    windows:
      imageName: 'ubuntu-16.04'
      target: "x86_64-pc-windows-gnu"

pool:
  vmImage: $(imageName)

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: Install rust
- task: Bash@3
  displayName: Build Project
  inputs:
    targetType: filePath
    noRc: false
    filePath: ./ci/publish.sh
- task: GitHubRelease@0
  displayName: Create Github Release
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    gitHubConnection: release
    repositoryName: '$(Build.Repository.Name)' 
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    assets: $(Build.SourcesDirectory)/target/releases/*
